export const TEAM_SCORING_LOADING = 'TEAM_SCORING_LOADING';
export const TEAM_SCORING_SUCCESS = 'TEAM_SCORING_SUCCESS';
export const TEAM_SCORING_FAIL = 'TEAM_SCORING_FAIL';

export const TEAM_ROSTER_LOADING = 'TEAM_ROSTER_LOADING';
export const TEAM_ROSTER_SUCCESS = 'TEAM_ROSTER_SUCCESS';
export const TEAM_ROSTER_FAIL = 'TEAM_ROSTER_FAIL';

export const PLAYER_SCORING_LOADING = 'PLAYER_SCORING_LOADING';
export const PLAYER_SCORING_SUCCESS = 'PLAYER_SCORING_SUCCESS';
export const PLAYER_SCORING_FAIL = 'PLAYER_SCORING_FAIL';
