import React from 'react';
import utilStyles from '../styles/utils.module.css';

const teamRoster = JSON.parse(`[
	{
			"_id": "hertlto01",
			"rank": "1",
			"name": "Tomas Hertl",
			"position": "C",
			"age": "27",
			"gamesPlayed": "8",
			"goals": "3",
			"assists": "4",
			"points": "7",
			"plusminus": "-6",
			"pims": "2",
			"evengoals": "1",
			"shortgoals": "0",
			"ppgoals": "2",
			"gwgoals": "0",
			"shots": "14",
			"shootingPercentage": "21.4",
			"toi": "161",
			"atoi": "20:07"
	},
	{
			"_id": "coutulo01",
			"rank": "2",
			"name": "Logan Couture",
			"position": "C",
			"age": "31",
			"gamesPlayed": "8",
			"goals": "3",
			"assists": "3",
			"points": "6",
			"plusminus": "0",
			"pims": "2",
			"evengoals": "2",
			"shortgoals": "0",
			"ppgoals": "1",
			"gwgoals": "0",
			"shots": "22",
			"shootingPercentage": "13.6",
			"toi": "159",
			"atoi": "19:51"
	},
	{
			"_id": "donatry01",
			"rank": "3",
			"name": "Ryan Donato",
			"position": "C",
			"age": "24",
			"gamesPlayed": "8",
			"goals": "3",
			"assists": "2",
			"points": "5",
			"plusminus": "-6",
			"pims": "2",
			"evengoals": "2",
			"shortgoals": "0",
			"ppgoals": "1",
			"gwgoals": "0",
			"shots": "19",
			"shootingPercentage": "15.8",
			"toi": "119",
			"atoi": "14:55"
	},
	{
			"_id": "kaneev01",
			"rank": "4",
			"name": "Evander Kane",
			"position": "LW",
			"age": "29",
			"gamesPlayed": "8",
			"goals": "2",
			"assists": "3",
			"points": "5",
			"plusminus": "-5",
			"pims": "20",
			"evengoals": "1",
			"shortgoals": "0",
			"ppgoals": "1",
			"gwgoals": "0",
			"shots": "20",
			"shootingPercentage": "10.0",
			"toi": "148",
			"atoi": "18:27"
	},
	{
			"_id": "labanke01",
			"rank": "5",
			"name": "Kevin Labanc",
			"position": "RW",
			"age": "25",
			"gamesPlayed": "8",
			"goals": "1",
			"assists": "4",
			"points": "5",
			"plusminus": "-1",
			"pims": "4",
			"evengoals": "1",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "24",
			"shootingPercentage": "4.2",
			"toi": "126",
			"atoi": "15:46"
	},
	{
			"_id": "meierti01",
			"rank": "6",
			"name": "Timo Meier",
			"position": "RW",
			"age": "24",
			"gamesPlayed": "8",
			"goals": "1",
			"assists": "4",
			"points": "5",
			"plusminus": "-4",
			"pims": "0",
			"evengoals": "1",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "25",
			"shootingPercentage": "4.0",
			"toi": "120",
			"atoi": "15:03"
	},
	{
			"_id": "burnsbr01",
			"rank": "7",
			"name": "Brent Burns",
			"position": "D",
			"age": "35",
			"gamesPlayed": "8",
			"goals": "2",
			"assists": "2",
			"points": "4",
			"plusminus": "-3",
			"pims": "8",
			"evengoals": "1",
			"shortgoals": "0",
			"ppgoals": "1",
			"gwgoals": "1",
			"shots": "26",
			"shootingPercentage": "7.7",
			"toi": "220",
			"atoi": "27:28"
	},
	{
			"_id": "nietoma01",
			"rank": "8",
			"name": "Matthew Nieto",
			"position": "LW",
			"age": "28",
			"gamesPlayed": "8",
			"goals": "2",
			"assists": "1",
			"points": "3",
			"plusminus": "-1",
			"pims": "2",
			"evengoals": "2",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "12",
			"shootingPercentage": "16.7",
			"toi": "108",
			"atoi": "13:27"
	},
	{
			"_id": "ferrama01",
			"rank": "9",
			"name": "Mario Ferraro",
			"position": "D",
			"age": "22",
			"gamesPlayed": "8",
			"goals": "0",
			"assists": "3",
			"points": "3",
			"plusminus": "-1",
			"pims": "2",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "14",
			"shootingPercentage": "0.0",
			"toi": "175",
			"atoi": "21:52"
	},
	{
			"_id": "karlser01",
			"rank": "10",
			"name": "Erik Karlsson",
			"position": "D",
			"age": "30",
			"gamesPlayed": "8",
			"goals": "0",
			"assists": "3",
			"points": "3",
			"plusminus": "-8",
			"pims": "2",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "12",
			"shootingPercentage": "0.0",
			"toi": "215",
			"atoi": "26:49"
	},
	{
			"_id": "gregono01",
			"rank": "11",
			"name": "Noah Gregor",
			"position": "C",
			"age": "22",
			"gamesPlayed": "6",
			"goals": "2",
			"assists": "0",
			"points": "2",
			"plusminus": "-4",
			"pims": "4",
			"evengoals": "2",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "13",
			"shootingPercentage": "15.4",
			"toi": "72",
			"atoi": "11:58"
	},
	{
			"_id": "leonajo01",
			"rank": "12",
			"name": "John Leonard",
			"position": "LW",
			"age": "22",
			"gamesPlayed": "7",
			"goals": "0",
			"assists": "2",
			"points": "2",
			"plusminus": "-5",
			"pims": "0",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "9",
			"shootingPercentage": "0.0",
			"toi": "91",
			"atoi": "13:04"
	},
	{
			"_id": "sorenma01",
			"rank": "13",
			"name": "Marcus Sorensen",
			"position": "RW",
			"age": "28",
			"gamesPlayed": "8",
			"goals": "1",
			"assists": "0",
			"points": "1",
			"plusminus": "0",
			"pims": "4",
			"evengoals": "1",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "12",
			"shootingPercentage": "8.3",
			"toi": "93",
			"atoi": "11:40"
	},
	{
			"_id": "gambrdy01",
			"rank": "14",
			"name": "Dylan Gambrell",
			"position": "C",
			"age": "24",
			"gamesPlayed": "5",
			"goals": "0",
			"assists": "1",
			"points": "1",
			"plusminus": "-2",
			"pims": "4",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "3",
			"shootingPercentage": "0.0",
			"toi": "73",
			"atoi": "14:35"
	},
	{
			"_id": "marlepa01",
			"rank": "15",
			"name": "Patrick Marleau",
			"position": "C",
			"age": "41",
			"gamesPlayed": "8",
			"goals": "0",
			"assists": "1",
			"points": "1",
			"plusminus": "-3",
			"pims": "0",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "4",
			"shootingPercentage": "0.0",
			"toi": "93",
			"atoi": "11:38"
	},
	{
			"_id": "simekra01",
			"rank": "16",
			"name": "Radim Simek",
			"position": "D",
			"age": "28",
			"gamesPlayed": "6",
			"goals": "0",
			"assists": "1",
			"points": "1",
			"plusminus": "-2",
			"pims": "0",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "3",
			"shootingPercentage": "0.0",
			"toi": "74",
			"atoi": "12:18"
	},
	{
			"_id": "dubnyde01",
			"rank": "17",
			"name": "Devan Dubnyk",
			"position": "G",
			"age": "34",
			"gamesPlayed": "5",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "0",
			"pims": "0",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "0",
			"shootingPercentage": "",
			"toi": "223",
			"atoi": "44:31"
	},
	{
			"_id": "handefr01",
			"rank": "18",
			"name": "Fredrik Händemark",
			"position": "C",
			"age": "27",
			"gamesPlayed": "1",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "-1",
			"pims": "0",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "0",
			"shootingPercentage": "",
			"toi": "10",
			"atoi": "9:44"
	},
	{
			"_id": "jonesma02",
			"rank": "19",
			"name": "Martin Jones",
			"position": "G",
			"age": "31",
			"gamesPlayed": "5",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "",
			"pims": "0",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "0",
			"shootingPercentage": "",
			"toi": "261",
			"atoi": "52:08"
	},
	{
			"_id": "kellmjo01",
			"rank": "20",
			"name": "Joel Kellman",
			"position": "F",
			"age": "26",
			"gamesPlayed": "1",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "-1",
			"pims": "2",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "1",
			"shootingPercentage": "0.0",
			"toi": "12",
			"atoi": "12:07"
	},
	{
			"_id": "knyzhni01",
			"rank": "21",
			"name": "Nikolai Knyzhov",
			"position": "D",
			"age": "22",
			"gamesPlayed": "8",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "-3",
			"pims": "4",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "5",
			"shootingPercentage": "0.0",
			"toi": "83",
			"atoi": "10:20"
	},
	{
			"_id": "melocni01",
			"rank": "22",
			"name": "Nicolas Meloche",
			"position": "D",
			"age": "23",
			"gamesPlayed": "1",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "1",
			"pims": "0",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "0",
			"shootingPercentage": "",
			"toi": "6",
			"atoi": "5:43"
	},
	{
			"_id": "middlja01",
			"rank": "23",
			"name": "Jacob Middleton",
			"position": "D",
			"age": "25",
			"gamesPlayed": "1",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "-2",
			"pims": "2",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "1",
			"shootingPercentage": "0.0",
			"toi": "9",
			"atoi": "8:44"
	},
	{
			"_id": "noesest01",
			"rank": "24",
			"name": "Stefan Noesen",
			"position": "RW",
			"age": "27",
			"gamesPlayed": "4",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "0",
			"pims": "2",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "3",
			"shootingPercentage": "0.0",
			"toi": "38",
			"atoi": "9:31"
	},
	{
			"_id": "vlasima01",
			"rank": "25",
			"name": "Marc-Edouard Vlasic",
			"position": "D",
			"age": "33",
			"gamesPlayed": "8",
			"goals": "0",
			"assists": "0",
			"points": "0",
			"plusminus": "-4",
			"pims": "2",
			"evengoals": "0",
			"shortgoals": "0",
			"ppgoals": "0",
			"gwgoals": "0",
			"shots": "7",
			"shootingPercentage": "0.0",
			"toi": "178",
			"atoi": "22:18"
	}
]`);

const TeamScoringStats = () => {
	return (
		<div className={utilStyles.tableContainer}>
			<table className={utilStyles.table}>
				<thead>
					<tr>
						<th>Player</th>
						<th>POS</th>
						<th>AGE</th>
						<th>GP</th>
						<th>G</th>
						<th>A</th>
						<th>PTS</th>
						<th>+/-</th>
						<th>PIM</th>
						<th>EV</th>
						<th>SG</th>
						<th>PP</th>
						<th>GW</th>
						<th>S</th>
						<th>S%</th>
						<th>TOI</th>
						<th>A_TOI</th>
					</tr>
				</thead>
				<tbody>
					{teamRoster.length > 0 &&
						teamRoster.map(player => (
							<tr key={player._id}>
								<td data_id='name'>{player.name}</td>
								<td data_id='position'>{player.position}</td>
								<td>{player.age}</td>
								<td>{player.gamesPlayed}</td>
								<td>{player.goals}</td>
								<td>{player.assists}</td>
								<td>{player.points}</td>
								<td>{player.plusminus}</td>
								<td>{player.pims}</td>
								<td>{player.evengoals}</td>
								<td>{player.shortgoals}</td>
								<td>{player.ppgoals}</td>
								<td>{player.gwgoals}</td>
								<td>{player.shots}</td>
								<td>{player.shootingPercentage}</td>
								<td>{player.toi}</td>
								<td>{player.atoi}</td>
							</tr>
						))}
				</tbody>
			</table>
		</div>
	);
};

export default TeamScoringStats;
